### ISSUE TITLE
Undefined reference to symbol when building in release mode

### ISSUE THREAD

**Issue by mythmon** [leftwm/leftwm-theme#14] opened 2021-07-07 18:50 UTC
When running `cargo build --release`, I get a lot of output, ending with:

```
  = note: /usr/bin/ld: /home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibssh2_sys-eff855945f40c808.rlib(libssh2_sys-eff855945f40c808.libssh2_sys.ao30mmkv-cgu.0.rcgu.o): undefined reference to symbol 'libssh2_exit'
          /usr/bin/ld: /usr/lib/libssh2.so.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
```

This problem doesn't happen with `cargo build`.

<details>
<summary>Full output of <code>cargo build --release<code></summary>
<pre><code>
$ cargo build --release
   Compiling leftwm-theme v0.1.1 (/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.0.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.1.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.10.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.11.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.12.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.13.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.14.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.15.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.2.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.3.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.4.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.5.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.6.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.7.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.8.rcgu.o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.leftwm_theme.3kq93u8g-cgu.9.rcgu.o" "-o" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/leftwm_theme-8d3a7226bb07fff5.3f1d5aqiyz7o4def.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps" "-L" "/usr/lib" "-L" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/build/libssh2-sys-c55a188dee5b04bb/out/build" "-L" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libpretty_env_logger-3912cfa91a11289a.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libenv_logger-6add424ba651d16f.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhumantime-8cd7d3e39ba94051.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libquick_error-c31f58ad57c7c49d.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libregex-1e3b068027cc28b0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libaho_corasick-349e3f397cadecb0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libregex_syntax-d410e2ec87367328.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libreqwest-c5ec81be5583d461.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhyper_tls-8ee1698d395b61eb.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libipnet-825fb763c8a388d0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtokio_native_tls-86c572a2c6595ddd.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libserde_urlencoded-254916c661e5a7cd.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libmime-901873007e56a724.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libencoding_rs-0fe99f9f294bc21b.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libbase64-ae60461090dc42a2.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libnative_tls-fa6c499adea3593e.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libopenssl-1434691a7ebe0eed.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libonce_cell-9b85574391bf34a9.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libforeign_types-80938dbf6e34a88e.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libforeign_types_shared-bcdb4be581881398.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhyper-344d6cc0612049b2.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libwant-bca4941820e6ee60.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtry_lock-ce7cd6afff058edc.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libsocket2-0ef9aa964ac1332c.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libh2-8198c96b0168a5a5.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtokio_util-4eea7648d962c285.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_sink-103cfc97520f809e.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhttparse-2a45fd510a2a3ce0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtower_service-a20fc3dfaae1cb83.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_channel-bdd906fc881c15f9.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libpin_project-97067532352dcd11.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtracing-e51f65b042c6a3aa.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtracing_core-2b7e0cb6533cd23c.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtokio-ce8262b8fe244ece.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libnum_cpus-8d7f2af5f75fb09e.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libmio-3058abc75b0ecf73.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhttp_body-55065c10ef3ee077.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_util-30f9fe9c448c15ca.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libmemchr-7e256388be913362.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_io-106709db30551542.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libslab-121cf67d62d23257.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libpin_project_lite-055bc18bc4ddf1f3.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_task-9fda5a06bbf07205.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libpin_utils-4535ef44dfde28d7.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfutures_core-6474ec0d5789f5ab.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhttp-944f0f5957a13221.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libbytes-91952ff9a318d476.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libfnv-73273c83591c1efd.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtoml-eccffa728cdf3ec3.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libserde_json-6f2d449cea074a60.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libryu-881c873fe921914b.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libitoa-17b73c5b2a14fe8c.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libserde-4407c63dc5c4150e.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libsemver-ea3232c3526f8199.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libedit_distance-ddfdf193d7a2004b.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libgit2-16f3a5d0c874b3b9.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libopenssl_probe-16c22baefdd3dc59.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liburl-6b2c423d48779e76.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libidna-9d240eaf6d043585.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libunicode_normalization-a998bcd2d3884958.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtinyvec-4e6897ac05f38663.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtinyvec_macros-eeee129e89c62e31.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libunicode_bidi-55072f2494202817.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libform_urlencoded-bfd1fc4df200d685.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libpercent_encoding-68b47103bab4898b.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libmatches-fd38d2675f8f2adb.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibgit2_sys-7994860df14dc145.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibssh2_sys-eff855945f40c808.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libopenssl_sys-f5f5fc8df9d351b9.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibz_sys-5a0e53b6bbf367e0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libcolored-bbf5589c448d2403.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libclap-0ac01000bc3b094f.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libstrsim-d848ef4897a1cb08.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libatty-2569b1293b756fb8.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibc-c07fa84751cf627a.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libvec_map-e53d344f35f15332.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libos_str_bytes-3a1d6a6d38a94e6f.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtermcolor-74decd4c0b5322a6.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libtextwrap-85aabec1a937c6d0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libunicode_width-af82d4e91c8cb3f3.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libindexmap-a7422841fc2095e5.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libhashbrown-a5686d19b5998b6d.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libbitflags-29209152dba883f0.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblazy_static-9ddb64e414b58b19.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libxdg-1e477afaa9f7c407.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblog-f9a361c01ade6320.rlib" "/home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/libcfg_if-048c2fa9f5217d0e.rlib" "-Wl,--start-group" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0a9489cf400f65e4.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-ff5dc44c66f8c479.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-3317c66a83501f9c.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-5d8dec11fc25537d.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-3af2a9328550e2a6.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3092e2ecef0f49f1.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-29b776c021389465.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e8873bd287db0d28.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-1171b49d77e47426.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-c29894d22dc88b51.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-796a7750df3d8218.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-ff7772d803d3e0de.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-dae3eac9cfa44200.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-0fa02f580e987af5.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-7f7254233be843ed.rlib" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1395c6db3d116086.rlib" "-Wl,--end-group" "/home/mythmon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b4bd87926720b651.rlib" "-Wl,-Bdynamic" "-lgit2" "-lssl" "-lcrypto" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: /home/mythmon/.cache/paru/clone/leftwm-theme-git/src/leftwm-theme-git/target/release/deps/liblibssh2_sys-eff855945f40c808.rlib(libssh2_sys-eff855945f40c808.libssh2_sys.ao30mmkv-cgu.0.rcgu.o): undefined reference to symbol 'libssh2_exit'
          /usr/bin/ld: /usr/lib/libssh2.so.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
</code></pre>
</details>

**Comment by mautamu** [comment] 2021-07-07 20:22
Which version of cargo/rustc are you using?

**Comment by mythmon** [comment] 2021-07-07 20:49
I was using 1.52 for the error above. Upgrading to 1.53 with `rustup update` seems to fix the problem.

**Comment by mythmon** [comment] 2021-07-07 21:04
Weirdly however, this did not fix the problem when doing `makepkg` (or using Paru), though I confirmed that it was using 1.53 as well.

**Comment by mautamu** [comment] 2021-07-07 23:55
Very curious. Paru for some reason doesn’t work for me, but I will try a fresh arch install this weekend and see if I can corner the issue.

**Comment by mautamu** [comment] 2021-07-17 05:15
Still unable to reproduce the issue with Paru-bin 1.7.3-1  and cargo 1.52.0 (69767412a 2021-04-21). Any more specifics on how to get it to happen? 

This appears to be libssh2 missing for you? Maybe we need to patch for vendored-openssl?

**Comment by mautamu** [comment] 2021-10-31 19:13
Closing this issue for now, if it persists please reopen.

**Closed as completed by mautamu** 2021-10-31 19:13 UTC
